// GENERATED CODE - DO NOT MODIFY BY HAND
// Bootstrapped manually; will be regenerated by `dart run build_runner build`.
//
// ignore_for_file: type=lint
// coverage:ignore-file

part of 'app_router.dart';

class SplashRoute extends PageRouteInfo<void> {
  const SplashRoute({List<PageRouteInfo>? children})
      : super(SplashRoute.name, initialChildren: children);

  static const String name = 'SplashRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const SplashPage());
}

class LanguageRoute extends PageRouteInfo<void> {
  const LanguageRoute({List<PageRouteInfo>? children})
      : super(LanguageRoute.name, initialChildren: children);

  static const String name = 'LanguageRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const LanguagePage());
}

class MainRoute extends PageRouteInfo<void> {
  const MainRoute({List<PageRouteInfo>? children})
      : super(MainRoute.name, initialChildren: children);

  static const String name = 'MainRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const MainPage());
}

class HomeRoute extends PageRouteInfo<void> {
  const HomeRoute({List<PageRouteInfo>? children})
      : super(HomeRoute.name, initialChildren: children);

  static const String name = 'HomeRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const HomePage()),
  );
}

class LoginRoute extends PageRouteInfo<void> {
  const LoginRoute({List<PageRouteInfo>? children})
      : super(LoginRoute.name, initialChildren: children);

  static const String name = 'LoginRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const LoginPage());
}

class RegisterRoute extends PageRouteInfo<void> {
  const RegisterRoute({List<PageRouteInfo>? children})
      : super(RegisterRoute.name, initialChildren: children);

  static const String name = 'RegisterRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const RegisterPage());
}

class MastersListRoute extends PageRouteInfo<MastersListRouteArgs> {
  MastersListRoute({
    Key? key,
    int? categoryId,
    String? categoryName,
    String? initialSearch,
    List<PageRouteInfo>? children,
  }) : super(
          MastersListRoute.name,
          args: MastersListRouteArgs(
            key: key,
            categoryId: categoryId,
            categoryName: categoryName,
            initialSearch: initialSearch,
          ),
          initialChildren: children,
        );

  static const String name = 'MastersListRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final args = data.argsAs<MastersListRouteArgs>(
        orElse: () => const MastersListRouteArgs(),
      );
      return WrappedRoute(
        child: MastersListPage(
          key: args.key,
          categoryId: args.categoryId,
          categoryName: args.categoryName,
          initialSearch: args.initialSearch,
        ),
      );
    },
  );
}

class MastersListRouteArgs {
  const MastersListRouteArgs({
    this.key,
    this.categoryId,
    this.categoryName,
    this.initialSearch,
  });
  final Key? key;
  final int? categoryId;
  final String? categoryName;
  final String? initialSearch;
}

class MasterDetailRoute extends PageRouteInfo<MasterDetailRouteArgs> {
  MasterDetailRoute({
    Key? key,
    required String idOrSlug,
    List<PageRouteInfo>? children,
  }) : super(
          MasterDetailRoute.name,
          args: MasterDetailRouteArgs(key: key, idOrSlug: idOrSlug),
          rawPathParams: {'idOrSlug': idOrSlug},
          initialChildren: children,
        );

  static const String name = 'MasterDetailRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final pathParams = data.inheritedPathParams;
      final args = data.argsAs<MasterDetailRouteArgs>(
        orElse: () => MasterDetailRouteArgs(
          idOrSlug: pathParams.getString('idOrSlug'),
        ),
      );
      return WrappedRoute(
        child: MasterDetailPage(key: args.key, idOrSlug: args.idOrSlug),
      );
    },
  );
}

class MasterDetailRouteArgs {
  const MasterDetailRouteArgs({this.key, required this.idOrSlug});
  final Key? key;
  final String idOrSlug;
}

class OrdersRoute extends PageRouteInfo<void> {
  const OrdersRoute({List<PageRouteInfo>? children})
      : super(OrdersRoute.name, initialChildren: children);

  static const String name = 'OrdersRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const MyOrdersPage()),
  );
}

class OrderDetailRoute extends PageRouteInfo<OrderDetailRouteArgs> {
  OrderDetailRoute({
    Key? key,
    required int id,
    List<PageRouteInfo>? children,
  }) : super(
          OrderDetailRoute.name,
          args: OrderDetailRouteArgs(key: key, id: id),
          rawPathParams: {'id': id},
          initialChildren: children,
        );

  static const String name = 'OrderDetailRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final pathParams = data.inheritedPathParams;
      final args = data.argsAs<OrderDetailRouteArgs>(
        orElse: () => OrderDetailRouteArgs(id: pathParams.getInt('id')),
      );
      return WrappedRoute(
        child: OrderDetailPage(key: args.key, id: args.id),
      );
    },
  );
}

class OrderDetailRouteArgs {
  const OrderDetailRouteArgs({this.key, required this.id});
  final Key? key;
  final int id;
}

class CreateOrderRoute extends PageRouteInfo<CreateOrderRouteArgs> {
  CreateOrderRoute({
    Key? key,
    int? preferredMasterId,
    List<PageRouteInfo>? children,
  }) : super(
          CreateOrderRoute.name,
          args: CreateOrderRouteArgs(
            key: key,
            preferredMasterId: preferredMasterId,
          ),
          initialChildren: children,
        );

  static const String name = 'CreateOrderRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final args = data.argsAs<CreateOrderRouteArgs>(
        orElse: () => const CreateOrderRouteArgs(),
      );
      return WrappedRoute(
        child: CreateOrderPage(
          key: args.key,
          preferredMasterId: args.preferredMasterId,
        ),
      );
    },
  );
}

class CreateOrderRouteArgs {
  const CreateOrderRouteArgs({this.key, this.preferredMasterId});
  final Key? key;
  final int? preferredMasterId;
}

class ProfileRoute extends PageRouteInfo<void> {
  const ProfileRoute({List<PageRouteInfo>? children})
      : super(ProfileRoute.name, initialChildren: children);

  static const String name = 'ProfileRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const ProfilePage());
}

class EditProfileRoute extends PageRouteInfo<void> {
  const EditProfileRoute({List<PageRouteInfo>? children})
      : super(EditProfileRoute.name, initialChildren: children);

  static const String name = 'EditProfileRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const EditProfilePage()),
  );
}

class ChangePasswordRoute extends PageRouteInfo<void> {
  const ChangePasswordRoute({List<PageRouteInfo>? children})
      : super(ChangePasswordRoute.name, initialChildren: children);

  static const String name = 'ChangePasswordRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const ChangePasswordPage()),
  );
}

class AddressesRoute extends PageRouteInfo<void> {
  const AddressesRoute({List<PageRouteInfo>? children})
      : super(AddressesRoute.name, initialChildren: children);

  static const String name = 'AddressesRoute';
  static PageInfo page =
      PageInfo(name, builder: (_) => const AddressesPage());
}

class AddressFormRoute extends PageRouteInfo<AddressFormRouteArgs> {
  AddressFormRoute({
    Key? key,
    AddressModel? initial,
    List<PageRouteInfo>? children,
  }) : super(
          AddressFormRoute.name,
          args: AddressFormRouteArgs(key: key, initial: initial),
          initialChildren: children,
        );

  static const String name = 'AddressFormRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final args = data.argsAs<AddressFormRouteArgs>(
        orElse: () => const AddressFormRouteArgs(),
      );
      return AddressFormPage(key: args.key, initial: args.initial);
    },
  );
}

class AddressFormRouteArgs {
  const AddressFormRouteArgs({this.key, this.initial});
  final Key? key;
  final AddressModel? initial;
}

class SettingsRoute extends PageRouteInfo<void> {
  const SettingsRoute({List<PageRouteInfo>? children})
      : super(SettingsRoute.name, initialChildren: children);

  static const String name = 'SettingsRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const SettingsPage());
}

class NotificationsRoute extends PageRouteInfo<void> {
  const NotificationsRoute({List<PageRouteInfo>? children})
      : super(NotificationsRoute.name, initialChildren: children);

  static const String name = 'NotificationsRoute';
  static PageInfo page =
      PageInfo(name, builder: (_) => const NotificationsPage());
}

class WalletRoute extends PageRouteInfo<void> {
  const WalletRoute({List<PageRouteInfo>? children})
      : super(WalletRoute.name, initialChildren: children);

  static const String name = 'WalletRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const WalletPage()),
  );
}

class ChatRoute extends PageRouteInfo<ChatRouteArgs> {
  ChatRoute({
    Key? key,
    required int orderId,
    List<PageRouteInfo>? children,
  }) : super(
          ChatRoute.name,
          args: ChatRouteArgs(key: key, orderId: orderId),
          rawPathParams: {'orderId': orderId},
          initialChildren: children,
        );

  static const String name = 'ChatRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final pathParams = data.inheritedPathParams;
      final args = data.argsAs<ChatRouteArgs>(
        orElse: () => ChatRouteArgs(orderId: pathParams.getInt('orderId')),
      );
      return WrappedRoute(
        child: ChatPage(key: args.key, orderId: args.orderId),
      );
    },
  );
}

class ChatRouteArgs {
  const ChatRouteArgs({this.key, required this.orderId});
  final Key? key;
  final int orderId;
}

class CallRoute extends PageRouteInfo<void> {
  const CallRoute({List<PageRouteInfo>? children})
      : super(CallRoute.name, initialChildren: children);

  static const String name = 'CallRoute';
  static PageInfo page = PageInfo(name, builder: (_) => const CallPage());
}

class AnnouncementsRoute extends PageRouteInfo<void> {
  const AnnouncementsRoute({List<PageRouteInfo>? children})
      : super(AnnouncementsRoute.name, initialChildren: children);

  static const String name = 'AnnouncementsRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const AnnouncementsPage()),
  );
}

class SmartSearchRoute extends PageRouteInfo<void> {
  const SmartSearchRoute({List<PageRouteInfo>? children})
      : super(SmartSearchRoute.name, initialChildren: children);

  static const String name = 'SmartSearchRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const SmartSearchPage()),
  );
}

class ForgotPasswordRoute extends PageRouteInfo<void> {
  const ForgotPasswordRoute({List<PageRouteInfo>? children})
      : super(ForgotPasswordRoute.name, initialChildren: children);

  static const String name = 'ForgotPasswordRoute';
  static PageInfo page =
      PageInfo(name, builder: (_) => const ForgotPasswordPage());
}

class ResetPasswordRoute extends PageRouteInfo<ResetPasswordRouteArgs> {
  ResetPasswordRoute({
    Key? key,
    String? token,
    String? login,
    List<PageRouteInfo>? children,
  }) : super(
          ResetPasswordRoute.name,
          args: ResetPasswordRouteArgs(key: key, token: token, login: login),
          rawQueryParams: {
            if (token != null) 'token': token,
            if (login != null) 'login': login,
          },
          initialChildren: children,
        );

  static const String name = 'ResetPasswordRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (data) {
      final query = data.queryParams;
      final args = data.argsAs<ResetPasswordRouteArgs>(
        orElse: () => ResetPasswordRouteArgs(
          token: query.getString('token', ''),
          login: query.getString('login', ''),
        ),
      );
      return ResetPasswordPage(
        key: args.key,
        token: args.token,
        login: args.login,
      );
    },
  );
}

class ResetPasswordRouteArgs {
  const ResetPasswordRouteArgs({this.key, this.token, this.login});
  final Key? key;
  final String? token;
  final String? login;
}

class RegisterRolePickerRoute extends PageRouteInfo<void> {
  const RegisterRolePickerRoute({List<PageRouteInfo>? children})
      : super(RegisterRolePickerRoute.name, initialChildren: children);

  static const String name = 'RegisterRolePickerRoute';
  static PageInfo page =
      PageInfo(name, builder: (_) => const RegisterRolePickerPage());
}

class RegisterMasterRoute extends PageRouteInfo<void> {
  const RegisterMasterRoute({List<PageRouteInfo>? children})
      : super(RegisterMasterRoute.name, initialChildren: children);

  static const String name = 'RegisterMasterRoute';
  static PageInfo page = PageInfo(
    name,
    builder: (_) => WrappedRoute(child: const RegisterMasterPage()),
  );
}

class VerifyPhoneRoute extends PageRouteInfo<void> {
  const VerifyPhoneRoute({List<PageRouteInfo>? children})
      : super(VerifyPhoneRoute.name, initialChildren: children);

  static const String name = 'VerifyPhoneRoute';
  static PageInfo page =
      PageInfo(name, builder: (_) => const VerifyPhonePage());
}
